services:
  - type: web
    name: donorbox-backend
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: donorbox-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: donorbox-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: donorbox-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400
      - key: MAIL_HOST
        value: mail.alphaseam.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: APP_BASE_URL
        value: https://donorbox-backend.onrender.com
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/donorbox-backend-0.0.1-SNAPSHOT.jar

databases:
  - name: donorbox-db
    databaseName: donorbox_db
    user: donorbox_user
    plan: starter
    region: oregon
